const QUOTES: string[] = [
  // --- Teamwork & Zusammenhalt (1-25) ---
  "Gemeinsam schaffen wir mehr als alleine — Teamwork macht den Unterschied.",
  "Zusammen sind wir nicht nur ein Team — wir sind eine Familie.",
  "Ein starkes Team braucht Menschen wie dich.",
  "Vertrauen im Team ist das Fundament für alles Große.",
  "Jeder Beitrag zählt — auch deiner. Besonders deiner.",
  "Wir sitzen alle im selben Boot — und du ruderst mit voller Kraft.",
  "Gemeinsam Berge versetzen? Machen wir. Jeden Tag.",
  "Das Beste an diesem Job sind die Menschen, mit denen du ihn machst.",
  "Einer für alle, alle für unsere Patienten.",
  "Du bist nicht allein — dein Team steht hinter dir.",
  "Zusammenarbeit ist keine Pflicht, sondern unsere Stärke.",
  "Wenn einer stolpert, fangen die anderen auf. So läuft das hier.",
  "Das Team ist nur so stark wie sein schwächstes Glied — und du bist alles andere als schwach.",
  "Kommunikation ist der Schlüssel — und du hast ihn in der Hand.",
  "Gute Kollegen machen aus Arbeit etwas, worauf man sich freut.",
  "Wir ziehen an einem Strang — und zwar in die richtige Richtung.",
  "Geteilte Arbeit ist halbe Arbeit. Geteilte Freude ist doppelte Freude.",
  "Ein Danke an die Kollegin nebenan kostet nichts, bewirkt aber viel.",
  "Heute ist ein guter Tag, um ein guter Teamplayer zu sein.",
  "Niemand ist perfekt — aber als Team kommen wir verdammt nah dran.",
  "Dein Lächeln ist ansteckend. Verbreite es im Büro.",
  "Hilfsbereitschaft ist keine Schwäche, sondern deine größte Stärke.",
  "Ein gutes Wort zur richtigen Zeit kann den ganzen Tag retten.",
  "Gemeinsam durch dick und dünn — das ist unser Motto.",
  "Der Erfolg gehört uns allen. Jeder einzelne trägt dazu bei.",

  // --- Motivation & Antrieb (26-50) ---
  "Ein guter Tag beginnt mit einem Lächeln und einem klaren Plan.",
  "Heute ist ein perfekter Tag, um etwas Großartiges zu erledigen.",
  "Jeder Tag ist eine neue Chance, etwas zu bewegen.",
  "Atme durch, priorisiere, und leg los — du schaffst das.",
  "Mach dir bewusst: deine Arbeit hat echten Impact.",
  "Kleine Fortschritte sind auch Fortschritte.",
  "Du hast schon härtere Tage gemeistert. Dieser wird ein Klacks.",
  "Motivation kommt manchmal erst beim Machen. Also fang einfach an.",
  "Dein Einsatz wird gesehen und geschätzt — auch wenn es nicht immer gesagt wird.",
  "Perfektion ist nicht das Ziel. Fortschritt schon.",
  "Starte nicht perfekt — starte jetzt.",
  "Was du heute erledigst, muss morgen niemand mehr machen.",
  "Erfolg ist die Summe kleiner Anstrengungen, die sich täglich wiederholen.",
  "Du bist stärker als du denkst. Und kompetenter sowieso.",
  "Lass dich nicht von der Menge der Aufgaben einschüchtern. Eins nach dem anderen.",
  "Jedes Telefonat, jede Mail, jeder Vorgang — alles hat einen Sinn.",
  "Denk nicht an die ganze Woche. Denk an heute. Heute packst du.",
  "Dein Durchhaltevermögen ist bewundernswert.",
  "Auch Montage können gut werden. Versprochen.",
  "Routine ist nicht langweilig — Routine gibt Sicherheit.",
  "Du machst einen Unterschied. Jeden. Einzelnen. Tag.",
  "Nicht jeder Tag wird perfekt. Aber jeder Tag zählt.",
  "Gib heute dein Bestes — mehr kann niemand verlangen.",
  "Energie folgt der Aufmerksamkeit. Fokussiere dich auf das Positive.",
  "Du bist der Grund, warum hier Dinge funktionieren.",

  // --- Büro & Organisation (51-75) ---
  "Ordnung im Büro, Klarheit im Kopf — du rockst das!",
  "Struktur schafft Freiheit — und du schaffst Struktur.",
  "Wer den Überblick behält, hat schon halb gewonnen.",
  "Ein aufgeräumter Schreibtisch ist ein aufgeräumter Geist.",
  "Listen machen glücklich. Vor allem wenn man Punkte abhaken kann.",
  "Priorisieren ist eine Kunst — und du bist der Künstler.",
  "Multitasking ist ein Mythos. Fokus ist die Wahrheit.",
  "Eine gute Ablage spart Stunden. Danke, dass du daran denkst.",
  "Deadlines sind keine Feinde — sie sind Motivatoren.",
  "Das Telefon klingelt? Jemand braucht deine Hilfe. Wie schön.",
  "Jede gut geschriebene Mail spart drei Rückfragen.",
  "Effizienz heißt nicht Hetze. Es heißt: klug arbeiten.",
  "Ein gut organisierter Tag ist ein entspannter Tag.",
  "Pause machen ist kein Luxus — es ist Notwendigkeit.",
  "Dein Posteingang ist kein Boss. Du entscheidest die Reihenfolge.",
  "Erst verstehen, dann handeln. Du machst das genau richtig.",
  "Weniger Drama, mehr Struktur. Das ist der Weg.",
  "Ein gutes System erspart tausend Entscheidungen.",
  "Nimm dir Zeit für das Wichtige, nicht nur für das Dringende.",
  "Plane den Tag, bevor der Tag dich plant.",
  "Ein kurzes Gespräch klärt mehr als zehn Mails.",
  "Fehler passieren — wichtig ist, was wir daraus lernen.",
  "Gründlichkeit schlägt Geschwindigkeit. Immer.",
  "Deine Sorgfalt schützt andere vor Problemen.",
  "Auch das komplizierteste Problem hat eine Lösung. Du findest sie.",

  // --- Pflege & Sinn (76-100) ---
  "Pflege beginnt im Büro — mit deiner Arbeit.",
  "Hinter jedem Formular steckt ein Mensch, dem wir helfen.",
  "Jeder erledigte Vorgang ist ein kleiner Sieg für unsere Patienten.",
  "Deine Arbeit gibt anderen Menschen Sicherheit und Halt.",
  "Ohne das Büro läuft keine Betreuung. Du bist unverzichtbar.",
  "Ein korrekt abgerechneter Fall bedeutet: ein Patient bekommt seine Hilfe.",
  "Du siehst die Patienten vielleicht nicht — aber sie profitieren von dir.",
  "Jede Budgetanfrage, die du stellst, sichert jemandem Unterstützung.",
  "Bürokratie nervt manchmal — aber sie schützt die Schwächsten.",
  "Was du hier tust, hat draußen echte Wirkung.",
  "Betreuer im Feld verlassen sich auf dich. Das ist eine Ehre.",
  "Du sorgst dafür, dass Hilfe dort ankommt, wo sie gebraucht wird.",
  "Jede Unterschrift, die du bearbeitest, steht für Vertrauen.",
  "Qualität in der Verwaltung = Qualität in der Betreuung.",
  "Unser Job ist nicht glamourös — aber er ist wichtig.",
  "Du bist die Brücke zwischen Betreuer und Patient.",
  "Abrechnungen sind trocken? Stimmt. Aber sie finanzieren echte Hilfe.",
  "Jemand da draußen hat heute einen besseren Tag wegen deiner Arbeit.",
  "Pflege ist Teamarbeit — und das Büro ist der Spielmacher.",
  "Danke, dass du diesen Job machst. Er wird nicht oft genug gewürdigt.",
  "Wer Pflege organisiert, pflegt auch — nur anders.",
  "Deine Genauigkeit rettet anderen Nerven und Zeit.",
  "Hinter den Zahlen stehen Schicksale. Du behandelst sie mit Respekt.",
  "Ein richtig ausgefülltes Formular ist ein Akt der Fürsorge.",
  "Du gibst dem Chaos Struktur. Das ist eine besondere Gabe.",

  // --- Wertschätzung (101-125) ---
  "Das Büro läuft, weil du läufst. Danke dafür!",
  "Du bist das Rückgrat des Teams — danke, dass du da bist.",
  "Geduld und Genauigkeit sind deine Superkräfte.",
  "Kaffee ist gut, aber dein Engagement ist besser.",
  "Ein Anruf, eine Lösung — manchmal ist es so einfach.",
  "Auch kleine Schritte bringen uns dem Ziel näher.",
  "Dein Einsatz wird nicht übersehen. Versprochen.",
  "Zuverlässigkeit ist selten — du hast sie im Überfluss.",
  "Danke, dass du auch die undankbaren Aufgaben übernimmst.",
  "Du bist der Grund, warum Dinge hier reibungslos laufen.",
  "Nicht jeder kann das, was du kannst. Sei stolz darauf.",
  "Dein Beitrag ist wie ein Puzzleteil — ohne dich fehlt was.",
  "Manchmal ist einfach da sein schon die halbe Miete.",
  "Du machst diesen Ort besser. Jeden Tag ein bisschen.",
  "Deine Arbeit hat Wert — auch wenn sie unsichtbar wirkt.",
  "Die besten Mitarbeiter sind die, auf die man sich verlassen kann. Du bist so einer.",
  "Ein ehrliches Danke: du machst das wirklich gut.",
  "Du bist nicht nur eine Arbeitskraft — du bist eine Bereicherung.",
  "Was du tust, tust du mit Herz. Das merkt man.",
  "Jeder Chef wünscht sich jemanden wie dich im Team.",
  "Dein Engagement fällt auf — im besten Sinne.",
  "Verlässlichkeit ist Gold wert. Du bist Gold wert.",
  "Manche Helden tragen keinen Umhang — sie sitzen im Büro.",
  "Danke für deine Geduld, auch wenn es mal stressig wird.",
  "Du verdienst mehr Anerkennung, als du bekommst. Hier ist ein Anfang.",

  // --- Humor & Leichtigkeit (126-150) ---
  "Montag? Kein Problem. Du hast Kaffee und Kompetenz.",
  "Wenn der Drucker streikt, bleibst du trotzdem cool. Respekt.",
  "Freitag kommt bestimmt. Bis dahin: Gas geben!",
  "Stress ist nur ein anderes Wort für viel zu tun. Und du tust es.",
  "Der Drucker ist unser gemeinsamer Feind. Zusammen besiegen wir ihn.",
  "Noch ein Meeting? Immerhin gibt es Kekse.",
  "Keep calm and Büro on.",
  "Kein WLAN im Paradies — aber dafür auch keine Mails.",
  "Mittwoch: der kleine Freitag. Du hast es fast geschafft!",
  "Tipp des Tages: ab und zu aufstehen, strecken, weitermachen.",
  "Dein Schreibtisch erzählt Geschichten. Hoffentlich gute.",
  "Heute schon gelächelt? Wenn nicht: jetzt.",
  "Büroarbeit ist Marathon, kein Sprint. Pacing ist alles.",
  "Das Wochenende wartet — aber erst machst du den Tag großartig.",
  "Irgendwo da draußen druckt jemand gerade etwas aus. Hoffen wir, es klappt.",
  "Excel-Tabellen sind auch eine Form von Kunst.",
  "Dein Kaffee wird kalt? Priorität 1. Sofort handeln.",
  "Jeder Arbeitstag hat 8 Stunden. Mach was draus!",
  "Auch ein chaotischer Tag kann produktiv enden.",
  "Kopfhörer auf, Fokus an — Büro-Superheld-Modus aktiviert.",
  "Wer viel macht, darf auch mal Fehler machen. Das ist menschlich.",
  "Der beste Zeitpunkt anzufangen war gestern. Der zweitbeste ist jetzt.",
  "Heute ist Halbzeit der Woche. Weiter so!",
  "To-Do-Liste leer? Unwahrscheinlich. Aber träumen darf man.",
  "Du bist der Beweis, dass Büroarbeit nicht langweilig sein muss.",

  // --- Selbstfürsorge (151-175) ---
  "Pause machen ist keine Schwäche — sondern klug.",
  "Denk daran: du bist mehr als deine To-Do-Liste.",
  "Auch du verdienst Wertschätzung. Gib sie dir selbst.",
  "Ein tiefer Atemzug kostet nichts und bringt viel.",
  "Gönn dir was Gutes heute. Du hast es verdient.",
  "Dein Wohlbefinden ist wichtig. Achte auf dich.",
  "Trinke genug Wasser. Dein Gehirn dankt es dir.",
  "Mittagspause an der frischen Luft? Beste Investition des Tages.",
  "Stress lässt sich nicht vermeiden — aber managen. Du kannst das.",
  "Sag auch mal Nein, wenn es zu viel wird. Das ist okay.",
  "Deine Gesundheit kommt vor jeder Deadline.",
  "Lachen ist die beste Medizin — auch im Büro.",
  "Ein kurzer Spaziergang in der Pause wirkt Wunder.",
  "Perfektionismus bremst. Gut genug ist oft gut genug.",
  "Schlaf ist produktiver als Überstunden. Merk dir das.",
  "Du musst nicht alles heute schaffen. Morgen ist auch noch ein Tag.",
  "Feierabend heißt Feierabend. Schalte wirklich ab.",
  "Deine Energie ist begrenzt. Setze sie weise ein.",
  "Es ist okay, einen schwierigen Tag zu haben.",
  "Selbstfürsorge ist kein Egoismus — es ist Voraussetzung.",
  "Wer sich selbst gut behandelt, behandelt auch andere gut.",
  "Kleine Rituale machen den Arbeitsalltag schöner.",
  "Atme ein. Atme aus. Weiter geht's.",
  "Du gibst jeden Tag dein Bestes. Das reicht.",
  "Vergiss nicht: nach der Arbeit kommt das Leben.",

  // --- Wachstum & Lernen (176-200) ---
  "Jeder Tag bringt eine neue Lektion — wenn du hinschaust.",
  "Aus Fehlern lernen ist keine Floskel. Es ist Realität.",
  "Wer fragt, lernt. Wer schweigt, rät.",
  "Neues auszuprobieren ist mutig. Mach weiter so.",
  "Routine ist gut — aber Wachstum passiert außerhalb der Komfortzone.",
  "Du warst letztes Jahr noch nicht so gut wie heute. Sieh den Fortschritt.",
  "Feedback ist ein Geschenk — auch wenn es sich nicht immer so anfühlt.",
  "Es ist in Ordnung, nicht alles zu wissen. Google hilft. Und Kollegen.",
  "Wissen teilen macht dich nicht ärmer — es macht alle reicher.",
  "Die beste Investition ist die in dich selbst.",
  "Veränderung ist unbequem, aber notwendig.",
  "Dein Potenzial hat keine Obergrenze.",
  "Neugier ist der Motor für Fortschritt.",
  "Wer aufhört besser zu werden, hört auf gut zu sein.",
  "Du lernst jeden Tag dazu — auch wenn du es nicht merkst.",
  "Der Weg zum Profi: machen, reflektieren, besser machen.",
  "Mut zur Lücke — und dann die Lücke füllen.",
  "Deine Erfahrung ist unbezahlbar. Gib sie weiter.",
  "Auch kleine Schulungen bringen große Erkenntnisse.",
  "Wachstum braucht Zeit. Sei geduldig mit dir.",
  "Heute weißt du mehr als gestern. Morgen mehr als heute.",
  "Dein Wissen ist ein Schatz — teile ihn großzügig.",
  "Fehler sind Lehrer in Verkleidung.",
  "Lernbereitschaft ist die wertvollste Eigenschaft.",
  "Du wirst jeden Tag ein bisschen besser. Das summiert sich.",

  // --- Fröhlich Dienste spezifisch (201-225) ---
  "Fröhlich Dienste — der Name ist Programm. Fröhlich arbeiten!",
  "Unsere Patienten verdienen das Beste. Du gibst es ihnen.",
  "Jede Abrechnung, die rausgeht, sichert jemandem Betreuung.",
  "Der Pflegesektor braucht Menschen wie dich. Danke.",
  "Wir machen keine gewöhnliche Arbeit — wir machen einen Unterschied.",
  "Fröhlich Dienste steht für Qualität. Du bist Teil davon.",
  "Unsere Betreuer verlassen sich auf das Büro. Wir liefern.",
  "Jeder VP-Antrag, den du bearbeitest, ermöglicht Verhinderungspflege.",
  "Leistungsnachweise sind mehr als Papier — sie sind Beweise für gute Arbeit.",
  "Die Krankenkasse wartet auf unsere Unterlagen. Zeigen wir, was wir können.",
  "Jeder Patient verdient korrekte Unterlagen. Du sorgst dafür.",
  "Fröhlich Dienste wächst — und du wächst mit.",
  "Unser Erfolg ist dein Erfolg.",
  "Du repräsentierst Fröhlich Dienste. Und du machst das super.",
  "Ambulante Pflege ist eine Herausforderung. Wir meistern sie gemeinsam.",
  "Deine Arbeit ermöglicht es Menschen, zuhause betreut zu werden.",
  "Pflege mit Herz — das fängt bei der Verwaltung an.",
  "Jeder Budgetnachweis sichert Leistungen für echte Menschen.",
  "Wir sind nicht nur ein Pflegedienst — wir sind eine Mission.",
  "Danke, dass du Teil der Fröhlich-Familie bist.",
  "Unsere Standards sind hoch. Mit dir erreichen wir sie.",
  "Du hältst den Laden am Laufen. Buchstäblich.",
  "Jede korrekte Rechnung stärkt das Vertrauen der Krankenkassen.",
  "Wir pflegen nicht nur Patienten — wir pflegen auch Beziehungen.",
  "Dein Beitrag zur Qualitätssicherung ist unbezahlbar.",

  // --- Jahreszeiten & Anlässe (226-260) ---
  "Neues Jahr, neue Energie — lass uns durchstarten.",
  "Der Frühling bringt frischen Wind — auch ins Büro.",
  "Sonne scheint? Genieß die Mittagspause draußen.",
  "Herbstzeit ist Erntezeit — auch für erledigte Aufgaben.",
  "Winter draußen, Wärme drinnen — gemütlich produktiv sein.",
  "Halbjahresmarke! Zeit für einen kleinen Rückblick.",
  "Das Quartal neigt sich — Endspurt!",
  "Jahresabschluss naht — du schaffst das mit links.",
  "Sommerloch? Gibt es bei uns nicht. Wir liefern immer.",
  "Ostern steht vor der Tür — belohne dich mit Schokolade.",
  "Jahresanfang: gute Vorsätze in gute Taten umsetzen.",
  "Urlaubszeit! Vertretungen laufen — dank deiner Planung.",
  "Weihnachtsstimmung im Büro: Kerze an, Chaos aus.",
  "Monatsanfang: neue Abrechnungsperiode, neues Glück.",
  "Freitagsfeeling: die Woche war gut. Du warst gut.",
  "Montagmorgen-Motivation: es sind nur fünf Tage. Los geht's.",
  "Die Tage werden länger — mehr Licht, mehr Tatendrang.",
  "Regenwetter? Perfekt zum fokussierten Arbeiten.",
  "Sommerhitze? Fenster auf, Ärmel hoch, Gas geben.",
  "Der erste Schnee? Drinnen ist es warm und produktiv.",
  "Feiertag bald? Vorher noch schnell die offenen Punkte abhaken.",
  "Brückentag gerettet? Dank deiner Vorarbeit!",
  "Karnevalsstimmung? Im Büro herrscht geordnete Fröhlichkeit.",
  "Advent: eine Kerze für jeden erledigten Meilenstein.",
  "Silvester naht: was hast du dieses Jahr alles geschafft? Viel!",
  "Frühlingsputz im Büro: Ordner aus, frische Ablage rein.",
  "Herbststurm draußen, Ruhe drinnen — konzentriert arbeiten.",
  "Nikolaus: kleine Aufmerksamkeiten für große Teamplayer.",
  "Grillsaison! Teamessen-Planung nicht vergessen.",
  "Die beste Jahreszeit? Jetzt. Weil du hier bist.",
  "Valentinstag: ein Herz für deine Arbeit!",
  "Tag der Arbeit: heute feiern wir, was wir jeden Tag tun.",
  "Erntedank: danke für deinen unermüdlichen Einsatz.",
  "Weltkindertag: auch unsere Kindkrankmeldungen zeigen — Familie geht vor.",
  "Internationaler Tag der Pflege: du bist Teil einer großartigen Branche.",

  // --- Weisheiten & Zitate (261-300) ---
  "Wer immer tut, was er schon kann, bleibt immer das, was er schon ist.",
  "Der Weg ist das Ziel — aber ankommen ist auch nicht schlecht.",
  "Qualität ist kein Zufall. Sie ist das Ergebnis harter Arbeit.",
  "In der Ruhe liegt die Kraft — und im zweiten Kaffee.",
  "Nicht der Wind bestimmt die Richtung, sondern das Segel.",
  "Wer kämpft, kann verlieren. Wer nicht kämpft, hat schon verloren.",
  "Das Geheimnis des Erfolgs: anfangen.",
  "Es gibt keine Abkürzungen zu Orten, die es wert sind.",
  "Sei die Veränderung, die du dir wünschst.",
  "Gut Ding will Weile haben — aber nicht zu lange.",
  "Weniger reden, mehr machen.",
  "Das einzige Unmögliche ist das, was du nicht versuchst.",
  "Heute ist der erste Tag vom Rest deiner Karriere.",
  "Probleme sind verkleidete Chancen.",
  "Wer A sagt, muss auch B sagen — aber nicht C, D, E...",
  "Mach es einfach. Oder einfach machen.",
  "Der frühe Vogel fängt den Wurm — der zweite Kaffee den Fokus.",
  "Lieber einmal richtig als dreimal fast.",
  "Wer langsam geht, kommt auch ans Ziel.",
  "Nicht die Last ist schwer, sondern die Art, wie wir sie tragen.",
  "Handle so, dass du morgen stolz auf heute bist.",
  "Fleiß schlägt Talent — wenn Talent nicht fleißig ist.",
  "Die beste Zeit etwas zu pflanzen war vor 20 Jahren. Die zweitbeste ist jetzt.",
  "Erfolg hat drei Buchstaben: TUN.",
  "Lebe so, dass dein zukünftiges Ich dir dankbar ist.",
  "Jede Reise beginnt mit einem einzigen Schritt.",
  "Geduld ist bitter, aber ihre Frucht ist süß.",
  "Wer aufgibt, hat schon verloren. Du gibst nie auf.",
  "Es ist nie zu spät, einen guten Tag zu haben.",
  "Heute ist ein guter Tag für einen guten Tag.",

  // --- Bonus: Extra-Sprüche bis 365 (301-365) ---
  "Vertraue dem Prozess. Die Ergebnisse kommen.",
  "Dein Schreibtisch, dein Königreich. Regiere weise.",
  "Auch Rom wurde nicht an einem Tag erbaut. Dein Projekt auch nicht.",
  "Manche Tage sind Diamanten, manche Steine. Beide sind wertvoll.",
  "Du bist der Held deiner eigenen Geschichte. Schreib ein gutes Kapitel.",
  "Jeder Experte war einmal Anfänger.",
  "Fokus auf Fortschritt, nicht auf Perfektion.",
  "Die schwierigsten Aufgaben bringen die größte Zufriedenheit.",
  "Dein Schreibtisch wartet. Mach ihn stolz.",
  "Weniger Sorgen, mehr Machen.",
  "Ein Problem ist eine Aufgabe in Verkleidung.",
  "Heute darfst du stolz auf dich sein. Einfach so.",
  "Dankbarkeit verändert die Perspektive. Was bist du heute dankbar?",
  "Jeder Klick, jeder Anruf, jede Mail — alles zählt.",
  "Du bist der Fels in der Brandung.",
  "Auch der längste Weg beginnt mit dem ersten Klick.",
  "Sei mutig genug, um Hilfe zu bitten. Das ist Stärke.",
  "Heute Abend wirst du froh sein, dass du heute Morgen angefangen hast.",
  "Dein Job ist wichtig. Du bist wichtig.",
  "Was du gibst, kommt zurück. Gib Gutes.",
  "Konzentration ist wie ein Muskel — trainiere ihn.",
  "Ablenkung ist der Feind. Fokus ist der Freund.",
  "Fang mit der unangenehmsten Aufgabe an. Der Rest ist Kinderspiel.",
  "Du bist flexibel, belastbar und klug. Die perfekte Kombi.",
  "Freundlichkeit kostet nichts und bringt alles.",
  "Respekt beginnt im Kleinen. Ein Gruß, ein Danke.",
  "Dein Beitrag mag unsichtbar sein — aber unverzichtbar.",
  "Mach dir keine Sorgen über morgen. Heute reicht.",
  "Wer lachen kann, kann auch arbeiten.",
  "Dein Talent liegt im Detail. Nutze es.",
  "Heute schon jemandem geholfen? Bestimmt.",
  "Du verdienst Anerkennung. Hier ist sie: Du bist großartig.",
  "Der beste Moment? Jetzt. Nutze ihn.",
  "Was immer du tust: tu es mit Überzeugung.",
  "Dein Tag. Deine Chance. Dein Erfolg.",
  "Ein Telefonat kann eine Welt verändern. Heb ab.",
  "Manche Aufgaben sind wie Puzzle — am Ende ergibt alles Sinn.",
  "Du bist das Zahnrad, das die Maschine am Laufen hält.",
  "Nichts ist unmöglich — es dauert nur manchmal etwas länger.",
  "Heute ist ein Geschenk. Deswegen heißt es Gegenwart.",
  "Genieße den Moment — auch im Büro.",
  "Du bist am richtigen Ort, zur richtigen Zeit.",
  "Das Beste kommt noch. Aber das Gute ist jetzt.",
  "Morgen beginnt der nächste Tag. Heute beenden wir diesen großartig.",
  "Dein letzter Arbeitstag? Weit weg. Mach das Beste aus dem heutigen.",
  "365 Tage. 365 Chancen. Heute ist eine davon.",
  "Du hast es bis hierher geschafft — das zeigt Stärke.",
  "Dein Engagement kennt keine Jahreszeit.",
  "Danke, dass du jeden Tag aufs Neue dein Bestes gibst.",
  "Ende des Jahres, Anfang des nächsten — du bist bereit.",
  "Ein ganzes Jahr voller Sprüche — und du verdienst jeden einzelnen.",
  "Morgen gibt es einen neuen Spruch. Und einen neuen großartigen Tag.",
  "Das war der letzte Spruch? Dann fangen wir von vorne an. Genau wie jeden Tag.",
  "Und falls du diesen Spruch schon mal gelesen hast: Er stimmt trotzdem.",
  "Plot Twist: DU bist der Motivationsspruch des Tages.",
];

export function getDailyQuote(): string {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const dayOfYear = Math.floor((now.getTime() - start.getTime()) / 86400000);
  return QUOTES[dayOfYear % QUOTES.length];
}

export default QUOTES;
